# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartTransitIO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartTransitIO
 # Flexbox Layout Manager Used By React Natve
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-shimmer', :path => '../node_modules/react-native-shimmer'

  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  pod 'react-native-branch', :path => '../node_modules/react-native-branch'
  pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  
  pod 'HockeySDK'



  target 'SmartTransitIO-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartTransitIOTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SmartTransitIO-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartTransitIO-tvOS

end
